apiVersion: v1
kind: Secret
metadata:
  name: {{ template "openshift-logforwarding-splunk.fullname" . }}
  namespace: {{ .Values.openshift.logging.namespace }}
  labels:
{{ include "openshift-logforwarding-splunk.labels" . | indent 4 }}
type: Opaque
data:
  hecToken: {{ required "Splunk HEC Token must be specified" .Values.forwarding.splunk.token | b64enc | quote }}


