apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Prune=false
  name: openshift-cluster-csi-drivers
  namespace: openshift-cluster-csi-drivers
spec:
  upgradeStrategy: Default


