apiVersion: v1
baseDomain: unit.apptoapp.net
compute:
  - hyperthreading: Enabled
    name: worker
    replicas: 3
    platform:
      vsphere:
        cpus: 2
        coresPerSocket: 2
        memoryMB: 8196
        osDisk:
          diskSizeGB: 120
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
  platform:
    vsphere:
      cpus: 4
      coresPerSocket: 2
      memoryMB: 16384
      osDisk:
        diskSizeGB: 120
metadata:
  name: strl-ocp-engg-1
platform:
  vsphere:
    vcenter: jvcewvvc9702.dsglobal.org
    username: s700232
    password: Ingcc123!
    datacenter: "CLOUD"
    defaultDatastore: PSTRJBCL_G15K1_OS-ENG_01
    folder: "/CLOUD/vm/RHO" #will use default folder
    #   diskType: thin not using thin disk
    network: "JBoss-BD_ENG_SBOX_VLAN3510_RHO_JBOSS"
    #network: "NonSensitiveLinux1/NonSensitiveLinux-GREENFIELD NON-PROD-SERVERS-3319"
    cluster: "STR JBOSS CLUSTER2"
    apiVIP: 10.204.173.5
    ingressVIP: 10.204.173.6
fips: false
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNDZjNzMyYTUwN2QxNDYzMjk1ODM3MDVkMmJkYzVkNzM6VkxOSDJPRFI5VFBJSFVYV0hLREdZQVJKSzRDUlNaMTdUUU0zOE9UUURCOVk2TzgzNlk1RDdYS1g4NEc4SVZKQg==","email":"Sagar.Reddy@qubit.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfNDZjNzMyYTUwN2QxNDYzMjk1ODM3MDVkMmJkYzVkNzM6VkxOSDJPRFI5VFBJSFVYV0hLREdZQVJKSzRDUlNaMTdUUU0zOE9UUURCOVk2TzgzNlk1RDdYS1g4NEc4SVZKQg==","email":"Sagar.Reddy@qubit.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWYzOWFlNmNhLWQ5ZDQtNGM5Ni04ZDgzLThkNzllNGI2MjUwNTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmxZalpoWlRCa01qSTFaRGMwTTJFd1lURTVaREkzWkRneE9UaGlZamRpTXlKOS5LcXRIWUdCbk4tY3YxVm9pREMzVjVid3JMUk5TcTFva3dpYk11Q0tEcVdMaWpfd2NTOEtwTjZIeXpJUHFaeUsyUXBtMDVnN21peTNXbDdKYWo0SkpzbTF0Rm10M2ptVVNQWlBLNGVXbjNuNzhwY0ctSHRjWHNlLVVLX3BtOHNzZEpGR2JLNURTSkFZWlp1djVlanp4WXF2Y0p5bk5QcDFaUk5vc2JscFNLNFpkVExKekNwS2dNeDZ3MkJFRVp0X2RidzhHSmZuQUdxUkJVNlpBOFk3RHlQcTU0R25UUUZQalFsb1NwZG5WeHpYWVFSRUw5RkpFNXdSM0FWRDcwUDA4VEtGQ2Z1akdqZHdoLUVUUVluNXdneS1sUUVvTjR1NzB6Y2lfbmdnY2k5dnRmR3ZaMTc0cFRieWtfLW9yRHVVclJGdFMzeS1hUF9fRVEwUnkxQkpCZHprZlRocmNGUHNkYlhvQ1VmekhJWTFTc0tLd0N0OG9QejAzdXdfRTlHVElZVW5XeTdtMUxXVlpRSFppcjFDOW5aS3lCaVBTOGQxRVZ4a2FpRXJObDZaZFJlUnBOblNLcVBpczJDeWlRLU8xUUQ1Y0FjWHJKbHdFUGZUWTdUbzV6YlkyYlJ5a0N6dnE2bDhOM1RMQklfWU95RVlQdnpTcHQ5REppR1dwNU4zVWNpcDFTak50b0ZTMThqZlgxM1g3dmVkYkU4dXFyTzRyekZkWWhjQkFwWFRKVEpNWGxlTldFUmx4RHhCTkNVazR2MVliSjJ5d2tPdEE2S01FSVVzRjlTcThmZTlxeDJabjA0cW5FcTZwb1J5R1JKaklTUVpnZ21OQU1VdFJNbVZXMHBTLTNvRkRTSEJleXgyT0gteE5xX1V0cFljRHNnZjVqOVlseTd2VVZJSQ==","email":"Sagar.Reddy@qubit.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWYzOWFlNmNhLWQ5ZDQtNGM5Ni04ZDgzLThkNzllNGI2MjUwNTpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSmxZalpoWlRCa01qSTFaRGMwTTJFd1lURTVaREkzWkRneE9UaGlZamRpTXlKOS5LcXRIWUdCbk4tY3YxVm9pREMzVjVid3JMUk5TcTFva3dpYk11Q0tEcVdMaWpfd2NTOEtwTjZIeXpJUHFaeUsyUXBtMDVnN21peTNXbDdKYWo0SkpzbTF0Rm10M2ptVVNQWlBLNGVXbjNuNzhwY0ctSHRjWHNlLVVLX3BtOHNzZEpGR2JLNURTSkFZWlp1djVlanp4WXF2Y0p5bk5QcDFaUk5vc2JscFNLNFpkVExKekNwS2dNeDZ3MkJFRVp0X2RidzhHSmZuQUdxUkJVNlpBOFk3RHlQcTU0R25UUUZQalFsb1NwZG5WeHpYWVFSRUw5RkpFNXdSM0FWRDcwUDA4VEtGQ2Z1akdqZHdoLUVUUVluNXdneS1sUUVvTjR1NzB6Y2lfbmdnY2k5dnRmR3ZaMTc0cFRieWtfLW9yRHVVclJGdFMzeS1hUF9fRVEwUnkxQkpCZHprZlRocmNGUHNkYlhvQ1VmekhJWTFTc0tLd0N0OG9QejAzdXdfRTlHVElZVW5XeTdtMUxXVlpRSFppcjFDOW5aS3lCaVBTOGQxRVZ4a2FpRXJObDZaZFJlUnBOblNLcVBpczJDeWlRLU8xUUQ1Y0FjWHJKbHdFUGZUWTdUbzV6YlkyYlJ5a0N6dnE2bDhOM1RMQklfWU95RVlQdnpTcHQ5REppR1dwNU4zVWNpcDFTak50b0ZTMThqZlgxM1g3dmVkYkU4dXFyTzRyekZkWWhjQkFwWFRKVEpNWGxlTldFUmx4RHhCTkNVazR2MVliSjJ5d2tPdEE2S01FSVVzRjlTcThmZTlxeDJabjA0cW5FcTZwb1J5R1JKaklTUVpnZ21OQU1VdFJNbVZXMHBTLTNvRkRTSEJleXgyT0gteE5xX1V0cFljRHNnZjVqOVlseTd2VVZJSQ==","email":"Sagar.Reddy@qubit.com"}}}'
sshKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILuGXat+2Aec5VaBafeT7JZ5fVoeh3YNDHH6hpy5dCra root@dstrlaae9201"
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIE0zCCA7ugAwIBAgIJANu+mC2Jt3uTMA0GCSqGSIb3DQEBCwUAMIGhMQswCQYD
  VQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTERMA8GA1UEBxMIU2FuIEpvc2Ux
  FTATBgNVBAoTDFpzY2FsZXIgSW5jLjEVMBMGA1UECxMMWnNjYWxlciBJbmMuMRgw
  FgYDVQQDEw9ac2NhbGVyIFJvb3QgQ0ExIjAgBgkqhkiG9w0BCQEWE3N1cHBvcnRA
  enNjYWxlci5jb20wHhcNMTQxMjE5MDAyNzU1WhcNNDIwNTA2MDAyNzU1WjCBoTEL
  MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExETAPBgNVBAcTCFNhbiBK
  b3NlMRUwEwYDVQQKEwxac2NhbGVyIEluYy4xFTATBgNVBAsTDFpzY2FsZXIgSW5j
  LjEYMBYGA1UEAxMPWnNjYWxlciBSb290IENBMSIwIAYJKoZIhvcNAQkBFhNzdXBw
  b3J0QHpzY2FsZXIuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
  qT7STSxZRTgEFFf6doHajSc1vk5jmzmM6BWuOo044EsaTc9eVEV/HjH/1DWzZtcr
  fTj+ni205apMTlKBW3UYR+lyLHQ9FoZiDXYXK8poKSV5+Tm0Vls/5Kb8mkhVVqv7
  LgYEmvEY7HPY+i1nEGZCa46ZXCOohJ0mBEtB9JVlpDIO+nN0hUMAYYdZ1KZWCMNf
  5J/aTZiShsorN2A38iSOhdd+mcRM4iNL3gsLu99XhKnRqKoHeH83lVdfu1XBeoQz
  z5V6gA3kbRvhDwoIlTBeMa5l4yRdJAfdpkbFzqiwSgNdhbxTHnYYorDzKfr2rEFM
  dsMU0DHdeAZf711+1CunuQIDAQABo4IBCjCCAQYwHQYDVR0OBBYEFLm33UrNww4M
  hp1d3+wcBGnFTpjfMIHWBgNVHSMEgc4wgcuAFLm33UrNww4Mhp1d3+wcBGnFTpjf
  oYGnpIGkMIGhMQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTERMA8G
  A1UEBxMIU2FuIEpvc2UxFTATBgNVBAoTDFpzY2FsZXIgSW5jLjEVMBMGA1UECxMM
  WnNjYWxlciBJbmMuMRgwFgYDVQQDEw9ac2NhbGVyIFJvb3QgQ0ExIjAgBgkqhkiG
  9w0BCQEWE3N1cHBvcnRAenNjYWxlci5jb22CCQDbvpgtibd7kzAMBgNVHRMEBTAD
  AQH/MA0GCSqGSIb3DQEBCwUAA4IBAQAw0NdJh8w3NsJu4KHuVZUrmZgIohnTm0j+
  RTmYQ9IKA/pvxAcA6K1i/LO+Bt+tCX+C0yxqB8qzuo+4vAzoY5JEBhyhBhf1uK+P
  /WVWFZN/+hTgpSbZgzUEnWQG2gOVd24msex+0Sr7hyr9vn6OueH+jj+vCMiAm5+u
  kd7lLvJsBu3AO3jGWVLyPkS3i6Gf+rwAp1OsRrv3WnbkYcFf9xjuaf4z0hRCrLN2
  xFNjavxrHmsH8jPHVvgc1VD0Opja0l/BRVauTrUaoW6tE+wFG5rEcPGS80jjHK4S
  pB5iDj2mUZH1T8lzYtuZy0ZPirxmtsk3135+CKNa2OCAhhFjE0xd
  -----END CERTIFICATE-----
