apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ws-b2b-accp-domain
- ws-b2b-accp-edge
- ws-b2c-accp-domain
- ws-b2c-accp-edge
- ws-b2c-accp-2
- ws-op-accp-domain
- ws-ivr-accp-domain
- ws-ivr-accp-edge
- ws-vpc-accp-domain
- ws-vpc-accp-edge
#- ws-mdm-accp-edge
- ws-mdm-accp-domain
- ws-hcentral-accp-domain
- ws-tms-accp
- ws-hav-accp-domain
- ws-sav-accp-domain
- ws-gnl-accp-domain
- ws-clmptb-accp-domain
- ws-vpa-accp-domain
- ws-gpd-accp-domain
- ws-esl-accp-domain
- ws-rwm-api-accp
- ws-b2bpais-accp-domain
- ws-swift-accp-domain
- ws-pnc-accp
- ws-ems-accp-domain
- ws-accon-accp-domain
- ws-caseupdt-accp-domain
- ws-b2b-admin-accp-edge
- ws-fdtpa-accp-domain
- ws-erp-accp-batch
- ws-ops-accp-edge
- ws-fndops-accp-edge
- ws-bko-accp-edge
- ws-fndops-accp-domain
- ws-sec-accp-edge
- ws-bko-accp-domain
- ws-ops-accp-domain

