apiVersion: v1
kind: Namespace
metadata:
  name: openshift-monitoring
  annotations:
    openshift.io/node-selector: ""
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops


