---
# tasks file for ocp_gitops

- name: ocp_gitops | roles/ocp_gitops/ocp_gitops_cluster-config_apps_validation_dynatrace.yaml | Openshift Gitops - Wait till Dynatrace application is created
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-dynatrace
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status is defined
  retries: 3
  delay: 5

- name: ocp_gitops | roles/ocp_gitops/ocp_gitops_cluster-config_apps_validation_dynatrace.yaml | Openshift Gitops - Wait 30sec before checking Dynatrace application status
  ansible.builtin.pause:
    seconds: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_dynatrace.yaml | Openshift Gitops - Get Dynatrace application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-dynatrace
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
  retries: 6
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_dynatrace.yaml | Openshift Gitops - Check Dynatrace application status
  ansible.builtin.assert:
    that:
      - ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
    fail_msg: "Dynatrace application not Healthy"
    success_msg: "Dynatrace application Healthy"

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_dynatrace.yaml | Openshift Gitops - Wait till Dynatrace activegate pod is running on infra nodes
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    kind: Pod
    label_selectors:
      - app.kubernetes.io/component=activegate
    namespace: dynatrace
    wait: yes
    wait_sleep: 10
    wait_timeout: 360
  register: ocp_gitops_pod_status
  until:
    - ocp_gitops_pod_status.resources[0].spec.nodeName is search ('infra')
  retries: 12
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_dynatrace.yaml | Openshift Gitops - Adding Dynatrace annotations to etcd service
  kubernetes.core.k8s:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    state: patched
    kind: Service
    name: etcd
    namespace: openshift-etcd
    definition:
      metadata:
        annotations:
          metrics.dynatrace.com/port: '9979'
          metrics.dynatrace.com/secure: 'true'
          metrics.dynatrace.com/scrape: 'true'
          metrics.dynatrace.com/tls.ca.crt: 'configmap:openshift-config:etcd-metric-serving-ca:ca-bundle.crt'
          metrics.dynatrace.com/tls.key: 'secret:openshift-config:etcd-metric-client:tls.key'
          metrics.dynatrace.com/tls.crt: 'secret:openshift-config:etcd-metric-client:tls.crt'


