---
# tasks file for ocp_gitops

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_cert-manager-operator.yaml | Openshift Gitops - Get cert-manager-operator application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-cert-manager-operator
    namespace: openshift-gitops
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status is defined
  retries: 10
  delay: 5

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_cert-manager-operator.yaml | Openshift Gitops - Wait 30sec before checking cert-manager-operator application status
  ansible.builtin.pause:
    seconds: 30

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_customcerts.yaml | Openshift Gitops - Wait till cert-manager-operator pod is running
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    kind: Pod
    label_selectors:
      - name=cert-manager-operator
    namespace: cert-manager-operator
    wait: yes
    wait_sleep: 10
    wait_timeout: 360
  register: ocp_gitops_pod_status
  until:
    - ocp_gitops_pod_status.resources[0].status.phase == "Running"
  retries: 10
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_cert-manager-operator.yaml | Openshift Gitops - Get cert-manager-operator application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-cert-manager-operator
    namespace: openshift-gitops
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
  retries: 10
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_cert-manager-operator.yaml | Openshift Gitops - Check cert-manager-operator application status
  ansible.builtin.assert:
    that:
      - ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
    fail_msg: "cert-manager-operator application not Healthy"
    success_msg: "cert-manager-operator application Healthy"

