apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      version: v1
      kind: IngressController
      name: sharded
      namespace: openshift-ingress-operator
    patch: |-
      - op: replace
        path: /spec/domain
        value: accp.apptoapp.net
      - op: add
        path: /spec/routeAdmission
        value: {"wildcardPolicy": "WildcardsAllowed"}
      - op: replace
        path: /spec/replicas
        value: 0


