apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ws-eb-sandbox-1

bases:
  - ../../../base
  - ../base

patches:
  - target:
      kind: RoleBinding
      name: project-qubit-web-support
    patch: |-
      - op: replace
        path: /subjects/0/name
        value: G-OCP-WEBOPS
  - target:
      kind: RoleBinding
      name: project-admins
    patch: |-
      - op: replace
        path: /subjects/0/name
        value: G-OCP-B2B-SDBX
      - op: replace
        path: /subjects/1/name
        value: G-OCP-B2C-SDBX
      - op: replace
        path: /subjects/2/name
        value: G-OCP-EB-SDBX
      - op: replace
        path: /subjects/3/name
        value: G-OCP-CORP-SDBX

#- target:
#    kind: ResourceQuota
#    name: resource-quota
#  patch: |-
#    - op: replace
#      path: /metadata/name
#      value: quota-team-a
#    - op: replace
#      path: /spec/hard/limits.cpu
#      value: 1
#    - op: replace
#      path: /spec/hard/services
#      value: 10
#- target:
#    kind: LimitRange
#    name: limit-range
#  patch: |-
#    - op: replace
#      path: /metadata/name
#      value: limit-team-a

