apiVersion: v1
items:
- apiVersion: imageregistry.operator.openshift.io/v1
  kind: Config
  metadata:
  spec:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            namespaces:
            - openshift-image-registry
            topologyKey: kubernetes.io/hostname
          weight: 100
    httpSecret: 50e6cc5b6a490086e7b770a7ba020eb1f1ae3c30a762036ecd91eb5b001279b8105f89fd7d07c517d84372d6d42c4e091074a5b26e69cd64e384e29bcd3a5364
    logLevel: Normal
    managementState: Managed
    nodeSelector:
      node-role.kubernetes.io/infra: ""
    observedConfig: null
    operatorLogLevel: Normal
    proxy: {}
    replicas: 1
    requests:
      read:
        maxWaitInQueue: 0s
      write:
        maxWaitInQueue: 0s
    rolloutStrategy: RollingUpdate
    storage:
      emptyDir: {}
      managementState: Managed
    tolerations:
    - effect: NoSchedule
      operator: Exists
    unsupportedConfigOverrides: null


