kind: LDAPSyncConfig
apiVersion: v1
url: ldaps://intldsp.entlds.apptoapp.net:636
insecure: false
bindDN: "CN=S700232,OU=Users,DC=IntLDSP,DC=EntLDS,DC=apptoapp,DC=net"
bindPassword:
ca: /home/j731198/qubitocp4-files/group-ca.crt
rfc2307:
  groupsQuery:
    baseDN: "DC=IntLDSP,DC=EntLDS,DC=apptoapp,DC=net"
    scope: sub
    filter: (CN=OCP*)
    derefAliases: never
  groupUIDAttribute: dn
  groupNameAttributes: [cn]
  groupMembershipAttributes: [member]
  usersQuery:
    baseDN: "DC=IntLDSP,DC=EntLDS,DC=apptoapp,DC=net"
    scope: sub
    derefAliases: never
  userUIDAttribute: dn
  userNameAttributes: [cn]
  tolerateMemberNotFoundErrors: false
  tolerateMemberOutOfScopeErrors: false
