apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: strl-ocp-engg-1-slblf
  name: strl-ocp-engg-1-slblf-infra-btw
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: strl-ocp-engg-1-slblf
      machine.openshift.io/cluster-api-machineset: strl-ocp-engg-1-slblf-infra
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: strl-ocp-engg-1-slblf
        machine.openshift.io/cluster-api-machine-role: infra
        machine.openshift.io/cluster-api-machine-type: infra
        machine.openshift.io/cluster-api-machineset: strl-ocp-engg-1-slblf-infra
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: "" 
      providerSpec:
        value:
          apiVersion: machine.openshift.io/v1beta1
          credentialsSecret:
            name: vsphere-cloud-credentials
          diskGiB: 120
          kind: VSphereMachineProviderSpec
          memoryMiB: 24576
          metadata:
          network:
            devices:
            - networkName: JBoss-BD_ENG_SBOX_VLAN3510_RHO_JBOSS
          numCPUs: 4
          numCoresPerSocket: 2
          snapshot: ""
          template: strl-ocp-engg-1-slblf-rhcos
          userDataSecret:
            name: worker-user-data
          workspace:
            datacenter: CLOUD
            datastore: PSTRJBCL_G15K1_OS-ENG_01
            folder: /CLOUD/vm/RHO
            resourcePool: /CLOUD/host/STR JBOSS CLUSTER2/Resources
            server: jvcewvvc9702.dsglobal.org


