apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

patches:
  - target:
      version: v1alpha1
      kind: Subscription
      name: conjur-follower-operator
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: "conjur-operator"
      - op: replace
        path: /spec/installPlanApproval
        value: "Manual"  
      - op: add
        path: /spec/startingCSV
        value: "conjur-follower-operator.v2.2.4"


