apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - snow-discovery-namespace.yaml
  - secret-qubitupgrade.yaml
  - secret-regcred.yaml
  - custom-root-ca.yaml
# #Added nodeselector and toleration for dynatrace-operator and dynatrace-webhook in dynatrace-openshift_v0.7.2.yaml
#      nodeSelector:
#        node-role.kubernetes.io/infra: ""
#      tolerations:
#      - effect: NoSchedule
#        key: node-role.kubernetes.io/infra
#        operator: Exists

