apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: cluster
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          namespaces:
          - openshift-image-registry
          topologyKey: kubernetes.io/hostname
        weight: 100
  logLevel: Normal
  managementState: Managed
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  operatorLogLevel: Normal
  proxy: {}
  replicas: 1
  rolloutStrategy: Recreate
  storage:
    managementState: Managed
    pvc:
      claim: image-registry-storage  
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/infra 
    operator: Exists


