kind: CronJob
apiVersion: batch/v1
metadata:
  name: cert-manager-secret-rotation
  namespace: cert-manager
  labels:
    app: cert-manager-secret-rotation
spec:
  schedule: '0 0 * * *'
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      labels:
        app: cert-manager-secret-rotation
    spec:
      backoffLimit: 5
      template:
        metadata:
          labels:
            app: cert-manager-secret-rotation
        spec:
          nodeSelector:
            node-role.kubernetes.io/infra: ''
          restartPolicy: OnFailure
          activeDeadlineSeconds: 600
          serviceAccountName: cert-manager
          terminationGracePeriodSeconds: 30
          securityContext: {}
          containers:
            - resources: {}
              terminationMessagePath: /dev/termination-log
              name: secret-rotation
              command:
                - /bin/bash
                - '-c'
                - >-
                  echo -e '\n\n---\nGet access-token for Venafi\n' &&
                  curl -k -s -X POST -H 'Content-Type: application/json' -d '{"username":"$(SID_USER)", "password":"$(SID_SECRET)", "client_id":"cert-manager.io", "scope":"certificate:manage,revoke"}' https://$(VENAFI_TENANT)/vedauth/authorize/oauth | grep -oP '(?<="access_token":")[^"]+(?=")' > /tmp/token &&
                  echo -e "\nAccess Token Generated\n" &&
                  oc patch secret $(CERT_MANAGER_SECRET_NAME) -n $(CERT_MANAGER_PROJECT) --type='json' -p='[{"op": "replace", "path": "/data/access-token", "value": '"$(echo -n $(cat /tmp/token) | base64 )"'}]' &&
                  echo -e '\n\n---\nCompleted\n'
              env:
              - name: SID_USER
                valueFrom:
                  secretKeyRef:
                    name: sid-creds
                    key: username
              - name: SID_SECRET
                valueFrom:
                  secretKeyRef:
                    name: sid-creds
                    key: password
              - name: VENAFI_TENANT
                value: {{ slice ( splitList "/" .Values.clusterIssuer.venafi.tppInstanceUrl ) 2 3 | join "" }}
              - name: CERT_MANAGER_PROJECT
                value: 'cert-manager'
              - name: CERT_MANAGER_SECRET_NAME
                value: 'venafi-tpp-secret'
              securityContext:
                capabilities:
                  drop:
                    - ALL
                privileged: false
              imagePullPolicy: Always
              terminationMessagePolicy: File
              image: 'registry.redhat.io/openshift4/ose-cli:latest'
          serviceAccount: cert-manager
          tolerations:
            - key: node-role.kubernetes.io/infra
              operator: Exists
              effect: NoSchedule
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1


