{{- if .Values.imagePullSecrets }}
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhcnRpZmFjdG9yeS52b3lhLm5ldCI6eyJ1c2VybmFtZSI6InM3MDAyMzIiLCJwYXNzd29yZCI6IkFQM1liU05taTNIYU1DdDRBeXQzc3Q4VkxwaiIsImF1dGgiOiJjemN3TURJek1qcEJVRE5aWWxOT2JXa3pTR0ZOUTNRMFFYbDBNM04wT0ZaTWNHbz0ifX19
kind: Secret
metadata:
  name: regcred
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
{{- end }}

