apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../base

patches:
- target:
    version: v1
  patch: |-
    - op: replace
      path: /metadata/namespace
      value: ws-ems-prod-domain

configMapGenerator:
- name: conjur-connect
  namespace: ws-ems-prod-domain
  options:
    annotations:
      argocd.argoproj.io/sync-wave: "7"
    labels:
      app.kubernetes.io/name: "conjur-connect-configmap"
      app.kubernetes.io/instance: "conjur-default-configmap"
      app.kubernetes.io/part-of: "conjur-config"
      conjur.org/name: "conjur-connect-configmap"
  literals:
  - CONJUR_ACCOUNT=conjur
  - CONJUR_APPLIANCE_URL=https://conjur-follower.cyberark-conjur.svc.cluster.local
  - CONJUR_AUTHN_URL=https://conjur-follower.cyberark-conjur.svc.cluster.local/authn-k8s/shk-ocp-prod-2
  - CONJUR_AUTHENTICATOR_ID=shk-ocp-prod-2
  files:
  - CONJUR_SSL_CERTIFICATE=conjur-leader-prod.pem
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous


