apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: anyuid-qubit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: anyuid-qubit
subjects:
  - kind: ServiceAccount
    name: qubit-apps-anyuid
    namespace: namespace
