apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: pod-restart-rb
  namespace: namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-restart-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: G-B2B

