apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-csi-driver-smb
  namespace: openshift-gitops
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: Gitops/manifests/cluster-config/csi-driver-smb
    repoURL: https://github.com/madhan-s1/OpenShift
    targetRevision: master
    helm:
      releaseName: csi-driver-smb
      valueFiles:
        - values-prod-2.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
