apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '2'
    traffic-policy.network.alpha.openshift.io/local-with-fallback: ""
  labels:
    app: router
    ingresscontroller.operator.openshift.io/owning-ingresscontroller: sharded
    router: router-nodeport-sharded
  name: router-nodeport-sharded
  namespace: openshift-ingress
spec:
  externalTrafficPolicy: Local
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30185
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30254
    port: 443
    protocol: TCP
    targetPort: https
  - name: metrics
    nodePort: 30726
    port: 1936
    protocol: TCP
    targetPort: metrics
  selector:
    ingresscontroller.operator.openshift.io/deployment-ingresscontroller: sharded
  sessionAffinity: None
  type: NodePort


