apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- dynatrace-namespace.yaml
- dynatrace-dynakube.yaml
- dynatrace-openshift_v0.13.yaml

# Added nodeselector and toleration for dynatrace-operator and dynatrace-webhook in dynatrace-openshift_v0.7.2.yaml
#      nodeSelector:
#        node-role.kubernetes.io/infra: ""
#      tolerations:
#      - effect: NoSchedule
#        key: node-role.kubernetes.io/infra
#        operator: Exists


