apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- infra-machineset.yaml
- worker-machineset.yaml
- customcerts.yaml
- storage-classes.yaml
- self-provisioner.yaml
- monitoring.yaml
- ldapidentityprovider.yaml
- ldapgroupsync.yaml
- imageregistry.yaml
- imageconfig.yaml
- logging.yaml
- logforwardingsplunk.yaml
- falcon-operator.yaml
- etcdbackup.yaml

