apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-conjur-app-ns
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: Gitops/manifests/cluster-config/conjur-app-ns/overlays/prod-1
    repoURL: https://github.com/madhan-s1/OpenShift
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
