apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-crowdstrike-kpagent
  namespace: openshift-gitops
spec:
  destination:
    namespace: falcon-kubernetes-protection
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: Gitops/manifests/cluster-config/crowdstrike-kpagent/cs-k8s-protection-agent
    repoURL: "https://github.com/madhan-s1/OpenShift"
    targetRevision: master
    helm:
      releaseName: kpagent
      parameters:
        - name: crowdstrikeConfig.clusterName
          value: "shk-ocp-prod-1"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
