apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-hugepages
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: Gitops/manifests/cluster-config/hugepages/overlays/prod-1
    repoURL: https://github.com/madhan-s1/OpenShift
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: machine.openshift.io
      kind: MachineSet
      jsonPointers:
        - /spec/replicas
