apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-namespace-unit-1
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: namespace-config
  source:
    path: Gitops/manifests-tenants/namespace-config/overlays/unit-2
    repoURL: https://github.com/madhan-s1/OpenShift
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
