apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-volume-qubitpaycloud-unit-edge-staging-service
  namespace:
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-volume-qubitpaycloud-unit-edge-staging-service
    volumeAttributes:
      source: \\pshkcdot02.dsglobal.org\qubitpaycloud_unit_staging
    nodeStageSecretRef:
      name: smbcreds
      namespace: kube-system
