apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: G-B2B
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: G-B2C
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: G-EB
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: G-CORP
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: APP-SUPPORT


