apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      version: v1
      kind: StorageClass
      name: thin-csi
    patch: |-
      - op: replace
        path: /parameters/StoragePolicyName
        value: openshift-storage-policy-strl-ocp-unit-1-7bgkf


