apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: ibm-security-verify-access-operator
  namespace: ibm-isva-operator
spec:
  channel: stable
  installPlanApproval: Manual
  name: ibm-security-verify-access-operator
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-security-verify-access-operator.v24.4.0
  config:
    resources:
      limits:
        cpu: 200m
        memory: 1028Mi
      requests:
        cpu: 100m
        memory: 512Mi 
    volumeMounts:
      - mountPath: /data
        name: ibm-security-verify-access-operator
        subPath: ibm-security-verify-access-operator
    volumes:
      - name: ibm-security-verify-access-operator
        persistentVolumeClaim:
          claimName: ibm-security-verify-access-operator


