---
# oc apply -f ocp-serviceaccount.yaml --namespace <namespace where application is deployed> 
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  name: test-app-sa 
  namespace: ws-sandbox-1 
  labels:
    app.kubernetes.io/name: "ws-sandbox-1-serviceaccount"
    app.kubernetes.io/instance: "ws-sandbox-1-serviceaccount"


