apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      version: v1alpha1
      kind: Subscription
      name: servicemeshoperator
    patch: |-
      - op: replace
        path: /spec/installPlanApproval
        value: Manual
      - op: add
        path: /spec/startingCSV
        value: "servicemeshoperator.v2.4.0"

