apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: smb-volume-erp-unit
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-volume-erp-unit
    volumeAttributes:
      source: \\pstrcdot23\cifs_fileproc_test1\
    nodeStageSecretRef:
      name: smbcred-erp
      namespace: ws-erp-unit-batch

---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: smb-volume-erp-unit-entdata
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-volume-erp-unit-entdata
    volumeAttributes:
      source: \\dsglobal.org\DFSRoot\EntData\fileproc_nonprod\dev\ 
    nodeStageSecretRef:
      name: smbcred-erp
      namespace: ws-erp-unit-batch

---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
  name: smb-volume-erp-unit-entapp
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-volume-erp-unit-entapp
    volumeAttributes:
      source: \\dsglobal.org\DFSRoot\entapp\AT_Oracle_dev\Dev\
    nodeStageSecretRef:
      name: smbcred-erp
      namespace: ws-erp-unit-batch



