apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: smbcred-erp
type: Opaque
data:
  domain: ZHNnbG9iYWwub3Jn
  password: cmYwQjJZM0dIUDhmQ2JUbg==
  username: czcxMDA4Mg==

