apiVersion: "v1"
kind: "LimitRange"
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: resource-limits
  namespace: new-namespace
spec:
  limits:
    - type: "Container"
      max:
        cpu: "2000m"
        memory: "2Gi"
     #min:
     #   cpu: "500m"
     #   memory: "512Mi"
      default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "500m"
        memory: "512Mi"


