apiVersion: v1
kind: ResourceQuota
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: compute-resources
  namespace: new-namespace
spec:
  hard:
    pods: "20" 
    requests.cpu: "20" 
    requests.memory: 24Gi 
    requests.ephemeral-storage: 2Gi 
    limits.cpu: "20" 
    limits.memory: 24Gi 
    limits.ephemeral-storage: 8Gi


