apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: venafi-tpp-cluster-issuer
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  venafi:
    zone: {{ .Values.clusterIssuer.venafi.policyFolder }}
    tpp:
      url: {{ .Values.clusterIssuer.venafi.tppInstanceUrl }}
      caBundle: {{ .Values.clusterIssuer.venafi.b64EncodedcaBundle }}
      credentialsRef:
        name: venafi-tpp-secret

