apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: venafi-tpp-secret
  namespace: cert-manager
data:
  access-token: {{ .Values.clusterIssuer.venafi.accessToken }}
type: Opaque

