apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
patches:
  - target:
      version: v1beta1
      kind: MachineSet 
      name: worker-1-machineset
      namespace: openshift-machine-api
    patch: |-
      - op: replace
        path: /metadata/name
        value: strl-ocp-proddr-1-bzvpn-worker-1
      - op: replace
        path: /metadata/labels/machine.openshift.io~1cluster-api-cluster
        value: strl-ocp-proddr-1-bzvpn
      - op: replace
        path: /spec/selector/matchLabels/machine.openshift.io~1cluster-api-cluster
        value: strl-ocp-proddr-1-bzvpn
      - op: replace
        path: /spec/selector/matchLabels/machine.openshift.io~1cluster-api-machineset
        value: strl-ocp-proddr-1-bzvpn-worker-1
      - op: replace
        path: /spec/template/metadata/labels/machine.openshift.io~1cluster-api-cluster
        value: strl-ocp-proddr-1-bzvpn
      - op: replace
        path: /spec/template/metadata/labels/machine.openshift.io~1cluster-api-machineset
        value: strl-ocp-proddr-1-bzvpn-worker-1
      - op: replace
        path: /spec/template/spec/providerSpec/value/network/devices/0/networkName
        value: JBoss-BD_PRODDR_VLAN3509_RHO_JBOSS
      - op: replace
        path: /spec/template/spec/providerSpec/value/template
        value: strl-ocp-proddr-1-bzvpn-rhcos
      - op: replace
        path: /spec/template/spec/providerSpec/value/workspace/datastore
        value: STR-56K1-JBOSS-OS-PROD_DR_04
      - op: replace
        path: /spec/template/spec/providerSpec/value/workspace/resourcePool
        value: /CLOUD/host/STR JBOSS CLUSTER2/Resources
      - op: replace
        path: /spec/replicas
        value: 2


