apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- etcd-bck-namespace.yaml
- etcd-bck-sa.yaml
- etcd-bck-clusterrole.yaml
- etcd-bck-clusterrolebinding.yaml
- etcd-bck-rolebinding-priv.yaml
- etcd-bck-clusterrole-scc-priv.yaml
- etcd-bck-cronjob.yaml


