{{ if .Values.appGroupNames}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: istio-read-rolebinding
  namespace: istio-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-system-read
subjects:
  {{- range $group := .Values.appGroupNames }}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $group }}
  {{- end }}
{{- end }}


