{{- if .Values.wildcardDomains }}
{{- if .Values.tls }}
kind: Secret
apiVersion: v1
metadata:
  name: sm-wildcard-cert
  namespace: istio-system
data:
  tls.crt: {{ .Values.tls.crt }}
  tls.key: {{ .Values.tls.key }}
type: kubernetes.io/tls

{{- else }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sm-wildcard-cert
  namespace: istio-system
spec:
  secretName: sm-wildcard-cert
  commonName: '*.{{ .Values.dnsName }}'
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - client auth
    - server auth
    - digital signature
    - key encipherment
  subject: 
    organizations:
      - 'qubit Services Company'
    organizationalUnits:
      - 'qubit Information Trust Services'
    localities:
      - 'Atlanta'
    provinces:
      - 'Georgia'
    countries:
      - 'US'
  duration: 17520h0m0s
  renewBefore: 168h0m0s
  dnsNames:
    - '*.{{ .Values.dnsName }}'
  issuerRef:
    kind: ClusterIssuer
    name: venafi-tpp-cluster-issuer
    group: cert-manager.io

{{- end}}
{{- end}}

