---
# vars file for ocp_gitops

ocp_gitops_openshift_host: https://api.shk-ocp-prod-2.apptoapp.net:6443
ocp_gitops_openshift_admin_user: kubeadmin
ocp_gitops_admins_group: G-OCP-PROD-CLUSTER-ADMIN


ocp_gitops_namespace_config_env:
  - prod-2


