---
# vars file for ocp_gitops

ocp_gitops_openshift_host: https://api.strl-ocp-unit-intg-1.intg.apptoapp.net:6443
ocp_gitops_openshift_admin_user: kubeadmin

ocp_gitops_namespace_config_env:
  - sandbox
  - unit-2
  - intg-1


