apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-volume-qubitpaycloud-prod-domain-archive-service
  namespace:
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-volume-qubitpaycloud-prod-domain-archive-service
    volumeAttributes:
      source: \\pshkcdot02.dsglobal.org\qubitpaycloud_prod
    nodeStageSecretRef:
      name: smbcreds
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-volume-qubitpaycloud-prod-domain-staging-service
  namespace:
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-volume-qubitpaycloud-prod-domain-staging-service
    volumeAttributes:
      source: \\pshkcdot02.dsglobal.org\qubitpaycloud_prod_staging
    nodeStageSecretRef:
      name: smbcreds
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-volume-qubitpaycloud-prod-domain-vrpbridge-service
  namespace:
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-volume-qubitpaycloud-prod-domain-vrpbridge-service
    volumeAttributes:
      source: \\pshkcdot02.dsglobal.org\vrpbridge_prod
    nodeStageSecretRef:
      name: smbcreds
      namespace: kube-system

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-volume-qubitpaycloud-prod-domain-vpc-payroll-file-recon
  namespace:
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-volume-qubitpaycloud-prod-domain-vpc-payroll-file-recon
    volumeAttributes:
      source: \\marrs.dsglobal.org\share\JOBREPT\VPC_Payroll_File_Recon\
    nodeStageSecretRef:
      name: smbcreds
      namespace: kube-system
