# The Authenticator RoleBinding grants permissions to the Conjur Authenticator ServiceAccount
# for the authenticator ClusterRole, which provides a list of Kubernetes API access permissions.
# This is required to validate application identities.
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: conjur-rolebinding
  namespace: cyberark-conjur
  labels:
    app.kubernetes.io/name: "conjur-rolebinding"
    app.kubernetes.io/component: "conjur-namespace-access"
    app.kubernetes.io/instance: "conjur-default-rolebinding"
    app.kubernetes.io/part-of: "conjur-config"
    conjur.org/name: "conjur-rolebinding"
subjects:
- kind: ServiceAccount
  name: conjur-serviceaccount
  namespace: cyberark-conjur
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conjur-clusterrole
  #namespace: cyberark-conjur


