- hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  become_user: jkadm
  vars_prompt:
    - name: ocp_gitops_environment
      prompt: "Which cluster do you want to validate?(engg-1, unit-1, intg-1, accp-1,  accp-2, proddr-1, prod-1, prod-2, rhacm-nprod)"
      private: no
    - name: ocp_gitops_openshift_admin_password
      prompt: "What is kubeadmin password?"
    - name: ocp_gitops_workers_scale_down
      prompt: "Do you need to recreate the worker nodes?(Yes/No)"
      private: no

  roles:
    - ocp_gitops


