apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: project-updatepod
rules:
- apiGroups:
  - '*'
  resources:
  - pods
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - pods/exec
  - pods/attach
  verbs:
  - create
  - get
- apiGroups:
  - '*'
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch

