apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "2"
  name: ldap-secret
  namespace: openshift-config
data:
  bindPassword: SW5nY2MxMjMh
type: Opaque


