apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#- ../../base
- olo-og.yaml
- olo-sub.yaml
- olo-namespace.yaml
- olo-instance.yaml

patches:
  - target:
      version: v1
      kind: ClusterLogging
      name: instance
      namespace: openshift-logging
    patch: |-
      # - op: replace
      #   path: /spec/logStore/elasticsearch/resources/limits/cpu
      #   value: 4500m
      # - op: replace
      #   path: /spec/logStore/elasticsearch/resources/limits/memory
      #   value: 16Gi
      # - op: replace
      #   path: /spec/logStore/elasticsearch/resources/requests/cpu
      #   value: 500m
      # - op: replace
      #   path: /spec/logStore/elasticsearch/resources/requests/memory
      #   value: 16Gi
      # - op: replace
      #   path: /spec/logStore/elasticsearch/storage/size
      #   value: 900G
      # - op: replace
      #   path: /spec/logStore/elasticsearch/storage/storageClassName
      #   value: thin-csi
      # - op: replace
      #   path: /spec/logStore/retentionPolicy/application/maxAge
      #   value: 1d
      # - op: replace
      #   path: /spec/logStore/retentionPolicy/audit/maxAge
      #   value: 1d
      # - op: replace
      #   path: /spec/logStore/retentionPolicy/infra/maxAge
      #   value: 1d
      - op: add
        path: /spec/collection
        value:
          tolerations:
          - effect: NoSchedule
            operator: Exists
          type: vector        
          resources:
            limits:
              memory: 2Gi
              cpu: 3000m
            requests:
              memory: 500Mi
              cpu: 500m        
  - target:
      version: v1alpha1
      kind: Subscription
      name: cluster-logging
    patch: |-
      - op: add
        path: /spec/installPlanApproval
        value: "Manual"  
  # - target:
  #     version: v1alpha1
  #     kind: Subscription
  #     name: elasticsearch-operator
  #   patch: |-
  #     - op: replace
  #       path: /spec/installPlanApproval
  #       value: "Manual"      


