apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: project-appadmin-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: project-appadmin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: G-OCP-Prod-AppAdmin

