fullnameOverride: openshift-logforwarding-splunk

openshift:
  logging:
    namespace: openshift-logging
    #elasticsearch:
    # port: 9200
  forwarding:
    audit:
      elasticsearch: false
      splunk: true
    app:
      elasticsearch: false
      splunk: false
      syslog: false
    infra:
      elasticsearch: false
      splunk: false

forwarding:
  splunk:
    # Specify Splunk server details and HEC Token
    token: 660111F4-30A0-4183-B3E4-6B26BACD4D0B
    protocol: https
    hostname: http-inputs-qubit.splunkcloud.com
    port: 443
    insecure: false
  syslog:
    # Specify syslog details
    name: openshift-logforwarding-syslog
    type: syslog
    hostname: oshift.unit.apptoapp.net
    port: 514
    facility: user
    rfc: RFC5424
    payloadKey: message
    severity: informational

pipelines:
  - detectMultilineErrors: true
    inputRefs:
      - application
    name: container-logs
    outputRefs:
      - openshift-logforwarding-splunk

  - inputRefs:
      - jbossApp
      - springApp
      - tomcatApp
      - jwsApp
      - nginx
    name: jboss-spring-tomcat-logs

    outputRefs:
      - openshift-logforwarding-syslog

  - inputRefs:
      - infrastructure
    name: infra-logs
    outputRefs:
      - openshift-logforwarding-splunk
  - inputRefs:
      - audit
    name: audit-logs

    outputRefs:
      - openshift-logforwarding-splunk
