apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
patches:
  - target:
      version: v1beta1
      kind: MachineSet
      name: worker-hp-2-machineset
      namespace: openshift-machine-api
    patch: |-
      - op: replace
        path: /metadata/name
        value: strl-ocp-accp-2-k8lf9-worker-hp-2
      - op: replace
        path: /metadata/labels/machine.openshift.io~1cluster-api-cluster
        value: strl-ocp-accp-2-k8lf9
      - op: replace
        path: /spec/selector/matchLabels/machine.openshift.io~1cluster-api-cluster
        value: strl-ocp-accp-2-k8lf9
      - op: replace
        path: /spec/selector/matchLabels/machine.openshift.io~1cluster-api-machineset
        value: strl-ocp-accp-2-k8lf9-worker-hp-2
      - op: replace
        path: /spec/template/metadata/labels/machine.openshift.io~1cluster-api-cluster
        value: strl-ocp-accp-2-k8lf9
      - op: replace
        path: /spec/template/metadata/labels/machine.openshift.io~1cluster-api-machineset
        value: strl-ocp-accp-2-k8lf9-worker-hp-2
      - op: replace
        path: /spec/template/spec/providerSpec/value/network/devices/0/networkName
        value: jboss-BD_ACCP_VLAN3530_RHO_JBOSS
      - op: replace
        path: /spec/template/spec/providerSpec/value/template
        value: strl-ocp-accp-2-k8lf9-rhcos
      - op: replace
        path: /spec/template/spec/providerSpec/value/workspace/datastore
        value: STR-56K1-JBOSS-ACCP02-05
      - op: replace
        path: /spec/template/spec/providerSpec/value/workspace/resourcePool
        value: /CLOUD/host/STR JBOSS CLUSTER2/Resources
      - op: replace
        path: /spec/template/spec/providerSpec/value/numCPUs
        value: 8
      - op: replace
        path: /spec/replicas
        value: 48

