kind: Secret
apiVersion: v1
metadata:
  name: github-oauth-config
  namespace: openshift-devspaces
  labels:
    app.kubernetes.io/part-of: che.eclipse.org
    app.kubernetes.io/component: oauth-scm-configuration
  annotations:
    che.eclipse.org/oauth-scm-server: github
    che.eclipse.org/scm-server-endpoint: https://github.qubit.net
    che.eclipse.org/scm-github-disable-subdomain-isolation: "false"
    argocd.argoproj.io/sync-wave: "3"
type: Opaque
stringData:
  id: 21b22a6409e72d4a11e9
  secret: 6c96b678d943247101878c92407a26a28258304b
