apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileproc
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /fileproc_nonprod/dev
    server: pstrcdot01.dsglobal.org

