apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileproc-test
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /fileproc_test_nfs
    server: pstrcdot01.dsglobal.org

