# Default values for cs-k8s-protection-agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.crowdstrike.com/kubernetes_protection/kpagent
  tag:
  pullPolicy: IfNotPresent
  envFrom:
    - configMapRef:
        name: agent-config

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Annotations to add to the service account
  name: ""
  annotations: {}

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

resources: {}

tolerations: []

affinity: {}

crowdstrikeConfig:
  clusterName: ""
  enableDebug: ""
  clientID: "2f77c26d26fb404d98dea5283f91f7a9"
  clientSecret: "VzyU4saFJwfN3AdjEW7o9bMxn6P2guc1QO58rX0m"
  env: "us-1"
  cid: "93b439ae3a954a05827741d862cb70eb"
  dockerAPIToken: "AKCp8mYodCrh9EuG8cow9it4M8DLXMHmZjAAcWU7fSYEeDWd5F2JAjUUEiNKRYiFJDHYjanyT"
  existingSecret: ""

