apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- api-certificate.yaml
- apps-certificate.yaml
- cabundle.yaml

patches:
  - target:
      version: v1
      kind: APIServer
      name: cluster
    patch: |-
      - op: replace
        path: /spec/servingCerts/namedCertificates/0/names/0
        value: "api.strl-ocp-unit-intg-1.intg.apptoapp.net"
  - target:
      version: v1
      kind: IngressController
      name: default
      namespace: openshift-ingress-operator
    patch: |-
      - op: add
        path: /spec/routeAdmission
        value: {"wildcardPolicy": "WildcardsAllowed"}
      - op: add
        path: /spec/routeSelector
        value: {"matchExpressions": [{"key":"type", "operator":"NotIn", "values":["sharded"]}]}
      - op: replace
        path: /spec/replicas
        value: 5


