apiVersion: v1
data:
  apiToken: ZHQwYzAxLkQ2N1lLS0ZLWDVFS0FUU0tXSDdaSFRLWS5PRVg3MzI2QU9SR1hJU1daTFJMQUVXTFdETk5ZVEhTWU1OVTZKM0ZRSkpHM1JGNFBDVkM1SzVZSjRZVllJSEQz
  dataIngestToken: ZHQwYzAxLklOVkxLSUc3WEE2TFYzQlJGMkVKUE1PNC42S1pMUDNFQUFBVVRaTUFWTDdDWVhPN0lWTjdFTVZaV0hWQlo3TFNDRE1aWVdXUlpUN0NGN0NJWUVLRDZPV1VD
kind: Secret
metadata:
  name: strl-ocp-accp-1
  namespace: dynatrace
type: Opaque


