global:
  resolve_timeout: 5m
inhibit_rules:
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = critical
    target_matchers:
      - severity =~ warning|info
  - equal:
      - namespace
      - alertname
    source_matchers:
      - severity = warning
    target_matchers:
      - severity = info
receivers:
  - name: Default
  - name: Watchdog
  - name: Critical
  - name: email-container-team
    email_configs:
      - to: DL-PaaS-PlaformTeam@qubit.com
        from: spartak.nasto@qubit.com
        smarthost: "smtp.apptoapp.net:25"
        hello: strl-ocp-prod-1
        require_tls: false
  - name: email-container-team-wa
    email_configs:
      - to: DL-PaaS-PlaformTeam@qubit.com
        from: spartak.nasto@qubit.com
        smarthost: "smtp.apptoapp.net:25"
        hello: strl-ocp-prod-1
        require_tls: false
route:
  group_by:
    - namespace
  group_interval: 5m
  group_wait: 30s
  receiver: Default
  repeat_interval: 12h
  routes:
    - matchers:
        - alertname = Watchdog
      receiver: Watchdog
    - matchers:
        - severity = critical
      receiver: Critical
    - receiver: email-container-team
      match:
        severity: critical
    - receiver: email-container-team-wa
      match:
        severity: warning
