apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: project-appadmin
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - delete
- apiGroups:
  - ""
  resources:
  - pods/log
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments/scale
  - statefulset/scale
  verbs:
  - get
  - update
  - patch



