apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: ibm-security-verify-access-operator
  namespace: ibm-isva-operator
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: thin-csi
  volumeMode: Filesystem


