defaultingress: ingressgateway
defaultegress: egressgateway
manageNetworkPolicy: true
loglevel: error

members:
  - ws-b2b-prod-edge
  - ws-b2b-prod-domain
  - ws-b2c-prod-edge
  - ws-b2c-prod-domain
  - ws-op-prod-domain
  - ws-ivr-prod-domain
  - ws-ivr-prod-edge
  - ws-vpc-prod-domain
  - ws-vpc-prod-edge
  - ws-mdm-prod-domain
  - ws-hcentral-prod-domain
  - ws-tms-prod
  - ws-hav-prod-domain
  - ws-sav-prod-domain
  - ws-gnl-prod-domain
  - ws-clmptb-prod-domain
  - ws-vpa-prod-domain
  - ws-gpd-prod-domain
  - ws-esl-prod-domain
  - ws-rwm-api-prod
  - ws-b2bpais-prod-domain
  - ws-swift-prod-domain
  - ws-pnc-prod
  - ws-ems-prod-domain
  - ws-accon-prod-domain
  - ws-caseupdt-prod-domain
  - ws-b2b-admin-prod-edge
  - ws-fdtpa-prod-domain
  - ws-ops-prod-edge
  - ws-fndops-prod-edge
  - ws-bko-prod-edge
  - ws-fndops-prod-domain
  - ws-sec-prod-edge
  - ws-bko-prod-domain
  - ws-ops-prod-domain
disableJaeger: true

smcpVersion: v2.6

wildcardDomains:
  - name: prod
    domain: sm.apps.shk-ocp-prod-2.apptoapp.net

routeloadbalance: true

istiod:
  resources:
    requests:
      cpu: 1
      memory: "1.6Gi"
  autoScaling:
    minReplicas: 3
    maxReplicas: 7
    
additionalIngress:
  - shortid: prod
    resources:
      cpu: 500m
      memory: 1500Mi
    limits:
      cpu: 2
      memory: 2Gi
    autoScaling:
      minReplicas: 3
      maxReplicas: 7
      
dnsName: "apps.shk-ocp-prod-2.apptoapp.net"
appGroupNames:
  - G-OCP-B2C-Prod
  - G-OCP-B2B-Prod
  - G-OCP-EB-Prod
  - G-OCP-CORP-Prod
  - G-OCP-IVR-Prod
  - G-OCP-HCENTRAL-Prod
  - G-OCP-EDPSHARED-Prod
  - G-OCP-OPS-Prod
  - G-OCP-FNDOPS-Prod
  - G-OCP-BKO-Prod
  - G-OCP-SEC-Prod

