apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: instance
  namespace: openshift-logging
spec:
  managementState: Managed
  logStore:
    lokistack:
      nodeCount: 3
      nodeSelector:
        node-role.kubernetes.io/infra: ""
      proxy:
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 256Mi
      redundancyPolicy: SingleRedundancy
      resources:
        limits:
          memory: 8Gi
        requests:
          cpu: 250m
          memory: 4Gi
      storage:
        size: 100G
        storageClassName: thin-csi
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/infra
        operator: Exists
    type: lokistack        

