apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  namespace: openshift-storage
  name: openshift-storage 
spec:
 targetNamespaces:
 - openshift-storage
 upgradeStrategy: Default

