apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
patches:
  - target:
      version: v1beta1
      kind: MachineSet 
      name: worker-hp-2-machineset 
      namespace: openshift-machine-api
    patch: |-
      - op: replace
        path: /metadata/name
        value: strl-ocp-unit-intg-1-67vfw-worker-hp-2
      - op: replace
        path: /metadata/labels/machine.openshift.io~1cluster-api-cluster
        value: strl-ocp-unit-intg-1-67vfw
      - op: replace
        path: /spec/selector/matchLabels/machine.openshift.io~1cluster-api-cluster
        value: strl-ocp-unit-intg-1-67vfw
      - op: replace
        path: /spec/selector/matchLabels/machine.openshift.io~1cluster-api-machineset
        value: strl-ocp-unit-intg-1-67vfw-worker-hp-2
      - op: replace
        path: /spec/template/metadata/labels/machine.openshift.io~1cluster-api-cluster
        value: strl-ocp-unit-intg-1-67vfw
      - op: replace
        path: /spec/template/metadata/labels/machine.openshift.io~1cluster-api-machineset
        value: strl-ocp-unit-intg-1-67vfw-worker-hp-2 
      - op: replace
        path: /spec/template/spec/providerSpec/value/network/devices/0/networkName
        value: JBoss-BD_UNIT_INTG_VLAN3511_RHO_JBOSS
      - op: replace
        path: /spec/template/spec/providerSpec/value/template
        value: strl-ocp-unit-intg-1-67vfw-rhcos
      - op: replace
        path: /spec/template/spec/providerSpec/value/workspace/datastore
        value: STR-56K1-JBOSS-INTG-03
      - op: replace
        path: /spec/template/spec/providerSpec/value/workspace/resourcePool
        value: /CLOUD/host/STR JBOSS CLUSTER1/Resources
      - op: replace
        path: /spec/template/spec/providerSpec/value/numCPUs
        value: 8
      - op: replace
        path: /spec/replicas
        value: 17


