# This ClusterRole defines the Kubernetes API access permissions that the Conjur
# authenticator will require in order to validate application identities.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: conjur-clusterrole
  labels:
    release: cluster-prep
    #heritage: Helm
    app.kubernetes.io/name: "conjur-clusterrole"
    app.kubernetes.io/component: "conjur-permissions"
    app.kubernetes.io/instance: "conjur-clusterrole"
    app.kubernetes.io/part-of: "conjur-config"
    conjur.org/name: "conjur-clusterrole"
    #helm.sh/chart: conjur-config-cluster-prep-0.2.0
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods", "serviceaccounts"]
    verbs: ["get", "list", "create", "update"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get"]
  - apiGroups: ["extensions"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "replicasets"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get", "list", "update"]


