apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: "odf-operator"
  namespace: "openshift-storage" 
spec:
  channel: "stable-4.15"
  source: "redhat-operators" 
  sourceNamespace: "openshift-marketplace"
  name: odf-operator
  installPlanApproval: Manual
  startingCSV: odf-operator.v4.15.8-rhodf 


