apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
   annotations:
    argocd.argoproj.io/sync-wave: "2"
    rbac.authorization.kubernetes.io/autoupdate: 'true'
   name: system:openshift:scc:privileged
rules:
  - verbs:
      - use
    apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    resourceNames:
      - privileged


