apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  name: pod-restart-role
  namespace: namespace
rules:
- apiGroups:
  - '*'
  resources:
  - pods
  verbs:
    - get
    - list
    - delete
  
  

