apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config-sm-controlplane
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: Gitops/manifests/cluster-config/sm-controlplane
    repoURL: https://github.com/madhan-s1/OpenShift
    targetRevision: master
    helm:
      releaseName: controlplane
      valueFiles:
        - values-unit-1.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
