apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: ldap-groupsync
spec:
  schedule: "35 2 * * *"
  providers:
    - ldap:
        credentialsSecret:
          name: ldap-group-sync
          namespace: group-sync-operator
        ca: /home/j731198/qubitocp4-files/ldap-ca.crt
        insecure: false
        rfc2307:
          groupMembershipAttributes:
            - member
          groupNameAttributes:
            - cn
          groupUIDAttribute: cn
          groupsQuery:
            baseDN: "DC=IntLDSP,DC=EntLDS,DC=apptoapp,DC=net"
            derefAliases: never
            filter: (CN=OCP*)
            scope: sub
          tolerateMemberNotFoundErrors: false
          tolerateMemberOutOfScopeErrors: false
          userNameAttributes:
            - cn
          userUIDAttribute: dn
          usersQuery:
            baseDN: "DC=IntLDSP,DC=EntLDS,DC=apptoapp,DC=net"
            derefAliases: never
            scope: sub
        url: ldaps://intldsp.entlds.apptoapp.net:636
      name: ldap
