apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edit-xldeploy
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"  
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: xldeploy
  namespace: default


