apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- pod-restart-role.yaml
- project-view-rb.yaml
- service-account.yaml
- service-account-anyuid.yaml
- anyuid_rb.yaml
- edit_rb.yaml
- view_rb.yaml
- pod-restart-rb.yaml
- istio-read-rolebinding.yaml
- project-appadmin-role.yaml
- project-appadmin-rb.yaml

secretGenerator:
- name: cacert
  files:
  - cacerts.keystore
  type: Opaque

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/sync-wave: "2"


