---
# tasks file for ocp_gitops

- debug:
    msg: "Openshift Gitops - Create and validate network-policies-config applications for {{ ocp_gitops_environment }} cluster"

- pause:
    seconds: 5

- name: ocp_gitops | ocp_gitops_network-policies-config_apps.yaml | Openshift Gitops - Create network-policy application
  kubernetes.core.k8s:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    state: present
    src: "../../Gitops/network-policies-config/applications/{{ item }}/base/network-policy.yaml"
  loop: "{{ ocp_gitops_namespace_config_env }}"

- name: ocp_gitops | ocp_gitops_network-policies-config_apps.yaml | Openshift Gitops - network-policy application validation
  ansible.builtin.include_tasks:
    file: ocp_gitops_network-policies-config_apps_validation_network-policy.yaml
  loop: "{{ ocp_gitops_namespace_config_env }}"


