---
# tasks file for ocp_gitops

- name: ocp_gitops |  ocp_gitops_cluster-config_apps_validation_ingress-controller-sharding.yaml | Openshift Gitops - Get Ingress controller sharding application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-ingress-controller-sharding
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status is defined
  retries: 3
  delay: 5

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_ingress-controller-sharding.yaml | Openshift Gitops - Wait 10sec before checking Ingress controller sharding application status
  ansible.builtin.pause:
    seconds: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_ingress-controller-sharding.yaml | Openshift Gitops - Get Ingress controller sharding application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-customcerts
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
  retries: 6
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_ingress-controller-sharding.yaml | Openshift Gitops - Check Ingress controller sharding application status
  ansible.builtin.assert:
    that:
      - ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
    fail_msg: "Ingress controller sharding application not Healthy"
    success_msg: "Ingress controller sharding application Healthy"
#
#- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_ingress-controller-sharding.yaml | Openshift Gitops - Wait till router pods of sharding ingress controller are running on infra nodes
#  kubernetes.core.k8s_info:
#    host: "{{ ocp_gitops_openshift_host }}"
#    validate_certs: no
#    kind: Pod
#    label_selectors:
#      - ingresscontroller.operator.openshift.io/deployment-ingresscontroller=sharded
#    namespace: openshift-ingress
#    wait: yes
#    wait_sleep: 10
#    wait_timeout: 360
#  register: ocp_gitops_pod_status
#  until:
#    - ocp_gitops_pod_status.resources[0].spec.nodeName is search ('infra')
#    - ocp_gitops_pod_status.resources[1].spec.nodeName is search ('infra')
#    - ocp_gitops_pod_status.resources[2].spec.nodeName is search ('infra')
#  retries: 12
#  delay: 10


