---
# tasks file for ocp_gitops

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_storage_classes.yaml | Openshift Gitops - Get Storage classes application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-storage-classes
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status is defined
  retries: 3
  delay: 5

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_storage_classes.yaml | Openshift Gitops - Wait 10sec before checking Storage classes application status
  ansible.builtin.pause:
    seconds: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_storage_classes.yaml | Openshift Gitops - Get Storage classes application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-storage-classes
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
  retries: 6
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_storage_classes.yaml | Openshift Gitops - Check Storage classes application status
  ansible.builtin.assert:
    that:
      - ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
    fail_msg: "Storage classes application not Healthy"
    success_msg: "Storage classes application Healthy"

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_storage_classes.yaml | Openshift Gitops -  Get ClusterOperator storage status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: v1
    kind: ClusterOperator
    name: storage
    validate_certs: no
  register: ocp_gitops_cluster_operator_status

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_storage_classes.yaml | Openshift Gitops -  Check ClusterOperator storage status
  when: item.type == "Degraded"
  ansible.builtin.assert:
    that:
      - item.status == "False"
    fail_msg: "Storage cluster operator Degraded"
    success_msg: "Storage cluster operator Healthy"
  loop: "{{ ocp_gitops_cluster_operator_status.resources[0].status.conditions }}"


