---
# tasks file for ocp_gitops

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_ldapidentityprovider.yaml | Openshift Gitops - Get LdapIDP application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-ldapidentityprovider
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status is defined
  retries: 3
  delay: 5

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_ldapidentityprovider.yaml | Openshift Gitops - Wait 10sec before checking LdapIDP application status
  ansible.builtin.pause:
    seconds: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_ldapidentityprovider.yaml | Openshift Gitops - Get LdapIDP application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-ldapidentityprovider
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
  retries: 6
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_ldapidentityprovider.yaml | Openshift Gitops - Check LdapIDP application status
  ansible.builtin.assert:
    that:
      - ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
    fail_msg: "LdapIDP application not Healthy"
    success_msg: "LdapIDP application Healthy"

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_ldapidentityprovider.yaml | Openshift Gitops - Wait 1min for the start of ClusterOperator authentication update
  ansible.builtin.pause:
    minutes: 1

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_ldapidentityprovider.yaml | Openshift Gitops - Wait until ClusterOperator authentication status is good
  ansible.builtin.shell: |
    oc get co authentication -o=jsonpath='{.status.conditions[?(@.type=="Degraded")].status},{.status.conditions[?(@.type=="Degraded")].status},{.status.conditions[?(@.type=="Degraded")].message}'
  register: ocp_gitops_cluster_operator_status
  until: ocp_gitops_cluster_operator_status.stdout == "False,False,All is well"
  retries: 20
  delay: 30

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_ldapidentityprovider.yaml | Openshift Gitops - Get ClusterOperator authentication status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: v1
    kind: ClusterOperator
    name: authentication
    validate_certs: no
  register: ocp_gitops_cluster_operator_status

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_ldapidentityprovider.yaml | Openshift Gitops -  Check ClusterOperator authentication status
  when: item.type == "Degraded"
  ansible.builtin.assert:
    that:
      - item.status == "False"
    fail_msg: "Authentication cluster operator Degraded"
    success_msg: "Authentication cluster operator Healthy"
  loop: "{{ ocp_gitops_cluster_operator_status.resources[0].status.conditions }}"


