---
# tasks file for ocp_gitops

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_etcdbackup.yaml | Openshift Gitops - Get Etcd backup application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-etcdbackup
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status is defined
  retries: 3
  delay: 5

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_etcdbackup.yaml | Openshift Gitops - Wait 10sec before checking Etcd backup application status
  ansible.builtin.pause:
    seconds: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_etcdbackup.yaml | Openshift Gitops - Get Etcd backup application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-etcdbackup
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
  retries: 6
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_etcdbackup.yaml | Openshift Gitops - Check Etcd backup application status
  ansible.builtin.assert:
    that:
      - ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
    fail_msg: "Etcd backup application not Healthy"
    success_msg: "Etcd backup application Healthy"

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_etcdbackup.yaml | Openshift Gitops - Get timestamp from the system
  shell: "date +%Y%m%d%H%M%S"
  register: ocp_gitops_tstamp

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_etcdbackup.yaml | Openshift Gitops - Job preparation for manual run of Etcd backup
  shell: >
    oc create job
    --from cronjob/openshift-backup
    "openshift-backup-{{ ocp_gitops_tstamp.stdout }}"
    -n ocp-backup-etcd
  register: result
  retries: 3
  delay: 5
  until: result.rc == 0

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_etcdbackup.yaml | Openshift Gitops - Start manual run of Etcd backup
  shell: >
    oc patch job
    "openshift-backup-{{ ocp_gitops_tstamp.stdout }}"
    -p '{"spec":{"ttlSecondsAfterFinished":864000}}'
    -n ocp-backup-etcd
  register: result
  retries: 3
  delay: 5
  until: result.rc == 0

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_etcdbackup.yaml | Openshift Gitops - Check result of manual run of Etcd backup
  shell: |
    oc get pods -l job-name=openshift-backup-{{ ocp_gitops_tstamp.stdout }} -n ocp-backup-etcd
  register: ocp_gitops_sync_pod
  changed_when: false
  retries: 12
  delay: 10
  until: ocp_gitops_sync_pod.stdout is search ('Completed')


