---
# tasks file for ocp_gitops

- name: ocp_gitops |  ocp_gitops_namespace-config_apps_validation_config-namespace.yaml| Openshift Gitops - Get config-namespace-{{ item }} application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-namespace-{{ item }}
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status is defined
  retries: 3
  delay: 5

- name: ocp_gitops | ocp_gitops_namespace-config_apps_validation_config-namespace.yaml | Openshift Gitops - Wait 10sec before checking config-namespace-{{ item }} application status
  ansible.builtin.pause:
    seconds: 10

- name: ocp_gitops | ocp_gitops_namespace-config_apps_validation_config-namespace.yaml | Openshift Gitops - Get config-namespace-{{ item }} application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-namespace-{{ item }}
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
  retries: 6
  delay: 10

- name: ocp_gitops | ocp_gitops_namespace-config_apps_validation_config-namespace.yaml | Openshift Gitops - Check config-namespace-{{ item }} application status
  ansible.builtin.assert:
    that:
      - ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
    fail_msg: "config-namespace-{{ item }} application not Healthy"
    success_msg: "config-namespace-{{ item }} application Healthy"


