---
# tasks file for ocp_gitops

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_worker-mft-machineset.yaml | Openshift Gitops - Get worker-mft machineset application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    #validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-worker-mft-machineset
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status is defined
  retries: 3
  delay: 5

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_worker-mft-machineset.yaml | Openshift Gitops - Wait 10sec before checking worker-mft machineset application status
  ansible.builtin.pause:
    seconds: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_worker-mft-machineset.yaml | Openshift Gitops - Get worker-mft machineset application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    #validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-worker-mft-machineset
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
  retries: 6
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_worker-mft-machineset.yaml | Openshift Gitops - Check worker-mft machineset application status
  ansible.builtin.assert:
    that:
      - ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
    fail_msg: "worker-mft machineset application not Healthy"
    success_msg: "worker-mft machineset application Healthy"

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_worker-mft-machineset.yaml | Openshift Gitops - Get cluster infrastructure id
  ansible.builtin.shell: |
    oc get -o jsonpath='{.status.infrastructureName}{"\n"}' infrastructure cluster
  register: ocp_gitops_infrastructure_id

- block:
    - name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_worker-mft-machineset.yaml | Openshift Gitops - Validate worker-mft machineset
      kubernetes.core.k8s_info:
        host: "{{ ocp_gitops_openshift_host }}"
        validate_certs: no
        api_version: machine.openshift.io/v1beta1
        kind: MachineSet
        name: "{{ ocp_gitops_infrastructure_id.stdout }}-worker-mft"
        namespace: openshift-machine-api
      register: ocp_gitops_worker-mft_machineset
      until:
        - ocp_gitops_worker-mft_machineset.resources[0].status.readyReplicas is defined
        - ocp_gitops_worker-mft_machineset.resources[0].status.readyReplicas == ocp_gitops_worker-mft_machineset.resources[0].status.replicas
      retries: 5 
      delay: 30

  rescue:

    - name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_worker-mft-machineset.yaml | Openshift Gitops - Validate worker-mft machineset status
      when: 
        - ocp_gitops_worker-mft_machineset.resources[0].status.readyReplicas is not defined
      debug:
        msg: "worker-mft machineset not ready"

    - name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_worker-mft-machineset.yaml | Openshift Gitops - Validate worker-mft machineset status
      when:
        - ocp_gitops_worker-mft_machineset.resources[0].status.readyReplicas is defined
        - ocp_gitops_worker-mft_machineset.resources[0].status.readyReplicas != ocp_gitops_worker-mft_machineset.resources[0].status.replicas
      debug:
        msg: "worker-mft machineset replicas are {{ ocp_gitops_worker-mft_machineset.resources[0].status.readyReplicas}} < desired replicas {{ ocp_gitops_worker-mft_machineset.resources[0].status.replicas }}"

    - name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_worker-mft-machineset.yaml | Openshift Gitops - Identified error in worker-mft machinesets validation
      ansible.builtin.set_fact:
        ocp_gitops_worker-mft_machineset_validation_error: true

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_worker-mft-machineset.yaml | Openshift Gitops - Error in worker-mft machinesets validation
  when: ocp_gitops_worker-mft_machineset_validation_error is defined
  ansible.builtin.fail:
    msg: "Error in worker-mft machinesets validation"

