---
# tasks file for ocp_gitops

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_config-conjur-app-ns.yaml | Openshift Gitops - Get conjur-app-ns application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-conjur-app-ns
    namespace: openshift-gitops
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status is defined
  retries: 3
  delay: 5

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_config-conjur-app-ns.yaml | Openshift Gitops - Wait 10sec before checking conjur-app-ns application status
  ansible.builtin.pause:
    seconds: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_config-conjur-app-ns.yaml | Openshift Gitops - Get conjur-app-ns application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-conjur-app-ns
    namespace: openshift-gitops
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
  retries: 6
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_config-conjur-app-ns.yaml | Openshift Gitops - Check conjur-app-ns application status
  ansible.builtin.assert:
    that:
      - ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
    fail_msg: "config-conjur-app-ns application not Healthy"
    success_msg: "config-conjur-app-ns application Healthy"


