---
# tasks file for ocp_gitops

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Get Hugepages 1 application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-hugepages-1
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status is defined
  retries: 3
  delay: 5

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Wait 10sec before checking Hugepages 1 application status
  ansible.builtin.pause:
    seconds: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Get Hugepages 1 application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-hugepages-1
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
  retries: 6
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Check Hugepages 1 application status
  ansible.builtin.assert:
    that:
      - ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
    fail_msg: "Hugepages 1 application not Healthy"
    success_msg: "Hugepages 1 application Healthy"

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Get cluster infrastructure id
  ansible.builtin.shell: |
    oc get -o jsonpath='{.status.infrastructureName}{"\n"}' infrastructure cluster
  register: ocp_gitops_infrastructure_id

- block:
    - name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Validate Worker-hp-1 machineset
      kubernetes.core.k8s_info:
        host: "{{ ocp_gitops_openshift_host }}"
        validate_certs: no
        api_version: machine.openshift.io/v1beta1
        kind: MachineSet
        name: "{{ ocp_gitops_infrastructure_id.stdout }}-worker-hp-1"
        namespace: openshift-machine-api
      register: ocp_gitops_worker_hp_1_machineset
      until:
        - ocp_gitops_worker_hp_1_machineset.resources[0].status.readyReplicas is defined
        - ocp_gitops_worker_hp_1_machineset.resources[0].status.readyReplicas == ocp_gitops_worker_hp_1_machineset.resources[0].status.replicas
      retries: 4 
      delay: 120

  rescue:

    - name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Validate Worker-hp-1 machineset status
      when: 
        - ocp_gitops_worker_hp_1_machineset.resources[0].status.readyReplicas is not defined
      debug:
        msg: "Worker-hp-1 machineset not ready"

    - name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Validate Worker-hp-1 machineset status
      when:
        - ocp_gitops_worker_hp-1machineset.resources[0].status.readyReplicas is defined
        - ocp_gitops_worker_hp_1_machineset.resources[0].status.readyReplicas != ocp_gitops_worker_hp_1_machineset.resources[0].status.replicas
      debug:
        msg: "Worker-hp-1 machineset replicas are {{ ocp_gitops_worker_hp_1_machineset.resources[0].status.readyReplicas}} < desired replicas {{ ocp_gitops_worker_hp_machineset.resources[0].status.replicas }}"

    - name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Identified error in Worker-hp-1 machinesets validation
      ansible.builtin.set_fact:
        ocp_gitops_worker_hp_1_machineset_validation_error: true

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Error in Worker-hp-1 machinesets validation
  when: ocp_gitops_worker_hp_1_machineset_validation_error is defined
  ansible.builtin.fail:
    msg: "Error in Worker-hp-1 machinesets validation"

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Get Worker-hp-1 nodes
  ansible.builtin.shell: |
    oc get node -l node-role.kubernetes.io/worker-hp-1= --no-headers=true | awk '{print $1}'
  register: ocp_gitops_worker_hp_1_nodes

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Collect Hugepages 1 setting
  ansible.builtin.shell: |
    oc get node "{{ item }}" -o jsonpath="{.status.allocatable.hugepages-2Mi}"
  loop: "{{ ocp_gitops_worker_hp_1_nodes.stdout_lines }}"
  register: ocp_gitops_worker_hp_nodes_hugepages_1

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_hugepages-1.yaml | Openshift Gitops - Verify Hugepages 1 setting
  ansible.builtin.assert:
    that:
      - item.stdout == "{{ ocp_gitops_worker_hp_hugepages-1 }}"
    fail_msg: "Worker-hp-1 node {{ item.item }} has a wrong hugepages setting"
    success_msg: "Hugepage for worker-hp-1 node {{ item.item }} ok"
  loop: "{{ ocp_gitops_worker_hp_nodes_hugepages_1.results }}"


