---
# tasks file for ocp_gitops

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_imageregistry.yaml | Openshift Gitops - Get Image registry application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-imageregistry
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status is defined
  retries: 3
  delay: 5

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_imageregistry.yaml | Openshift Gitops - Wait 10sec before checking Image registry application status
  ansible.builtin.pause:
    seconds: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_imageregistry.yaml | Openshift Gitops - Get Image registry application status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: config-imageregistry
    namespace: openshift-gitops
    validate_certs: no
  register: ocp_gitops_application_status
  until: ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
  retries: 6
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_imageregistry.yaml | Openshift Gitops - Check Image registry application status
  ansible.builtin.assert:
    that:
      - ocp_gitops_application_status.resources[0].status.health.status == "Healthy"
    fail_msg: "Image registry application not Healthy"
    success_msg: "Image registry application Healthy"

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_imageregistry.yaml | Openshift Gitops - Wait till Image registry pod is running on infra nodes
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    kind: Pod
    label_selectors:
      - docker-registry=default
    namespace: openshift-image-registry
    wait: yes
    wait_sleep: 10
    wait_timeout: 360
  register: ocp_gitops_pod_status
  until: 
    - ocp_gitops_pod_status.resources[0].spec.nodeName is search ('infra')
  retries: 12
  delay: 10

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_imageregistry.yaml | Openshift Gitops -  Get ClusterOperator image-registry status
  kubernetes.core.k8s_info:
    host: "{{ ocp_gitops_openshift_host }}"
    validate_certs: no
    api_version: v1
    kind: ClusterOperator
    name: image-registry
    validate_certs: no
  register: ocp_gitops_cluster_operator_status

- name: ocp_gitops | ocp_gitops_cluster-config_apps_validation_imageregistry.yaml | Openshift Gitops -  Check ClusterOperator image-registry status
  when: item.type == "Degraded"
  ansible.builtin.assert:
    that:
      - item.status == "False"
    fail_msg: "Image registry cluster operator Degraded"
    success_msg: "Image registry cluster operator Healthy"
  loop: "{{ ocp_gitops_cluster_operator_status.resources[0].status.conditions }}"


