apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - target:
      version: v1
      kind: ClusterLogging
      name: instance
      namespace: openshift-logging
    patch: |-
      - op: replace
        path: /spec/logStore/elasticsearch/resources/limits/memory
        value: 16Gi
      - op: replace
        path: /spec/logStore/elasticsearch/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/logStore/elasticsearch/resources/requests/memory
        value: 16Gi
      - op: replace
        path: /spec/logStore/elasticsearch/storage/size
        value: 500G
      - op: replace
        path: /spec/logStore/elasticsearch/storage/storageClassName
        value: thin-csi
      - op: replace
        path: /spec/logStore/retentionPolicy/application/maxAge
        value: 2d
      - op: replace
        path: /spec/logStore/retentionPolicy/audit/maxAge
        value: 2d
      - op: replace
        path: /spec/logStore/retentionPolicy/infra/maxAge
        value: 2d


