apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nonprod-edit-deployment-clusterrole
rules:
- apiGroups:
  - '*'
  resources:
  - deployments
  verbs:
    - get
    - list
    - watch
    - update
    - patch
    - create
- apiGroups:
  - '*'
  resources:
  - pods
  - pods/log
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - pods/exec
  - pods/attach
  verbs:
  - create
  - get

