---
# Source: conjur-config-cluster-prep/templates/serviceaccount.yaml
# This ServiceAccount provides the Kubernetes RBAC identity for the Conjur Kubernetes authenticator
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations: 
    argocd.argoproj.io/sync-wave: "8"
  name: conjur-serviceaccount
  namespace: ws-sandbox-1
  labels:
    #elease: cluster-prep
    #eritage: Helm
    app.kubernetes.io/name: "conjur-serviceaccount"
    app.kubernetes.io/component: "conjur-kubernetes-identity"
    app.kubernetes.io/instance: "conjur-serviceaccount"
    app.kubernetes.io/part-of: "conjur-config"
    conjur.org/name: "conjur-serviceaccount"
    argocd.argoproj.io/managed-by: "openshift-gitops"
    #elm.sh/chart: conjur-config-cluster-prep-0.2.1


