apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: hugepages-2
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Boot time configuration for hugepages
      include=openshift-node
      [bootloader]
      cmdline_openshift_node_hugepages=hugepagesz=2M hugepages=8192
    name: openshift-node-hugepages

  recommend:
  - machineConfigLabels:
      machineconfiguration.openshift.io/role: "worker-hp-2"
    priority: 30
    profile: openshift-node-hugepages


