apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: custom-ca
    namespace: openshift-config
    files:
      - apps/ca-bundle.crt

secretGenerator:
  - name: wildapps
    namespace: openshift-ingress
    files:
      - apps/tls.crt
      - apps/tls.key
    type: kubernetes.io/tls
  - name: qubitapi
    namespace: openshift-config
    files:
      - api/tls.crt
      - api/tls.key
    type: kubernetes.io/tls

generatorOptions:
  disableNameSuffixHash: true
  annotations:
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "2"

patches:
  - target:
      version: v1
      kind: APIServer
      name: cluster
    patch: |-
      - op: replace
        path: /spec/servingCerts/namedCertificates/0/names/0
        value: "api.strl-ocp-rhacm.apptoapp.net"
  - target:
      version: v1
      kind: IngressController
      name: default
      namespace: openshift-ingress-operator
    patch: |-
      - op: add
        path: /spec/routeAdmission
        value: {"wildcardPolicy": "WildcardsAllowed"}
      - op: add
        path: /spec/routeSelector
        value: {"matchExpressions": [{"key":"type", "operator":"NotIn", "values":["sharded"]}]}
      - op: replace
        path: /spec/replicas
        value: 3
