apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ws-b2b-unit-domain
- ws-b2b-unit-edge
- ws-b2b-unit-ui
- ws-b2c-unit-domain
- ws-b2c-unit-edge
- ws-b2c-unit-ui
- ws-op-unit-domain
- ws-ivr-unit-domain
- ws-ivr-unit-edge
- ws-vpc-unit-domain
- ws-vpc-unit-edge
- ws-vpc-unit-ui
- ws-mpm-unit-domain
- ws-mdm-unit-edge
- ws-mdm-unit-domain
- ws-tms-unit
- ws-accon-unit-domain
- ws-b2b-admin-unit-ui
- ws-b2b-admin-unit-edge

