apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-volume-erp-accp
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-volume-erp-accp
    volumeAttributes:
      source: \\pstrcdot23\cifs_fileproc_test1\
    nodeStageSecretRef:
      name: erpcreds
      namespace: kube-system
      
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-volume-erp-accp-entdata
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-volume-erp-accp-entdata
    volumeAttributes:
      source: \\dsglobal.org\DFSRoot\EntData\fileproc_nonprod\accp\ 
    nodeStageSecretRef:
      name: erpcreds
      namespace: kube-system

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: smb-volume-erp-accp-entapp
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    volumeHandle: smb-volume-erp-accp-entapp
    volumeAttributes:
      source: \\dsglobal.org\DFSRoot\entapp\AT_Oracle_dev\QA\
    nodeStageSecretRef:
      name: erpcreds
      namespace: kube-system

